MyFirstWebAPP-DMWM/Controllers/APIControllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFirstWebAPP_DMWM.Models;
using MyFirstWebAPP_DMWM.Services;

namespace MyFirstWebAPP_DMWM.Controllers.APIControllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class CategoryController : ControllerBase
    {
        private readonly ICatgegoryService icatgegoryService;
        public CategoryController(ICatgegoryService icatgegoryService)
        {
            this.icatgegoryService = icatgegoryService;
        }

        [HttpGet("categories")]
        public async Task<IActionResult> getCategories()
        {
            var categories = await icatgegoryService.getallcategories();
            return Ok(categories);
        }
        [HttpPost]
        public async Task<IActionResult> CreateCategorie(CategoryDTO category)
        {
            var categorie = await icatgegoryService.CreateCategory(category);
            return Ok(categorie);
        }
        [HttpPut("{id}")]
        public async Task<IActionResult> EditCategorie(int id, Category category)
        {
            if (!ModelState.IsValid) return BadRequest();
            var categorie = await icatgegoryService.EditCategory(id,category);
            return Ok(categorie);
        }
        [HttpDelete("{id}")]
        public async Task<IActionResult> DeleteCategorie(int id)
        {
           
            var categorie = await icatgegoryService.DeleteCategory(id);
            return Ok(categorie);
        }
        [HttpGet("subcate")]
        public async Task<IActionResult> GetSubCategorie()
        {

            var categorie = await icatgegoryService.GetSubCategoriesByCategoryName();
            return Ok(categorie);
        }


    }
}

MyFirstWebAPP-DMWM/Controllers/MenuController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyFirstWebAPP_DMWM.Data;
using MyFirstWebAPP_DMWM.Models;

namespace MyFirstWebAPP_DMWM.Controllers
{
    public class MenuController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<ApplicationUser> _usermanager;
        public MenuController(ApplicationDbContext _db, UserManager<ApplicationUser> _usermanager)
        {
            this._db = _db;
            this._usermanager = _usermanager;
        }
        public IActionResult MenuListByUser()
        {
            var currentuser = _usermanager.GetUserId(User);
            var menus = _db.menuLists.Where(x => x.UserId == currentuser)
                .ToList();
            return View(menus);
        }
    }
}

MyFirstWebAPP-DMWM/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyFirstWebAPP_DMWM.Models;

namespace MyFirstWebAPP_DMWM.Controllers
{
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> _usermanager;
        private readonly RoleManager<IdentityRole> _rolemanager;
        public UserController(UserManager<ApplicationUser> _usermanager, RoleManager<IdentityRole> _rolemanager)
        {
            this._usermanager = _usermanager;
            this._rolemanager = _rolemanager;
        }
        //Lister tous les utilisateurs de notre application
        public IActionResult Index()
        {
            var users = _usermanager.Users;
            return View(users);
        }
        public IActionResult IndexRoles()
        {
            var roles = _rolemanager.Roles;
            return View(roles);
        }
    }
}

MyFirstWebAPP-DMWM/Views/Shared/_CreateButtonPartial.cshtml
<p>
    <a asp-action="Create"><i class="fas fa-plus-circle"></i>Create New</a>
</p>

MyFirstWebAPP-DMWM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MyFirstWebAPP_DMWM</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap-lux.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MyFirstWebAPP_DMWM</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Menu" asp-action="MenuListByUser">Menus</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="IndexRoles">roles</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MyFirstWebAPP_DMWM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>